import { expect, test } from '@playwright/test'
import path from 'node:path'
import os from 'node:os'

const ledgerKey = 'laundry-mountain:phase1:v1'
const sessionsKey = 'laundry-mountain:game-sessions:v1'
const evidence = path.join(os.tmpdir(), 'laundry-mountain-manual-session')

test('confirmed batches drive the climb, survive reload and finish honestly without camera', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/?view=home')
  await page.evaluate(() => localStorage.setItem('laundry-mountain:field-report:v1','preserve failed physical report'))
  await page.getByRole('button',{name:'Start a Laundry Session',exact:true}).click()
  await expect(page.getByRole('button',{name:'Bank this batch'})).toBeVisible()
  await expect(page.locator('video')).toHaveCount(0)
  await expect(page.locator('.reference-climb-world:visible')).toBeVisible()
  await page.screenshot({path:path.join(evidence,'session-phone.png'),fullPage:true})
  await page.getByRole('button',{name:'Bank this batch'}).click()
  await page.getByLabel('Completed items',{exact:true}).fill('0')
  await expect(page.getByRole('button',{name:/Confirm & climb/})).toBeDisabled()
  await page.getByLabel('Completed items',{exact:true}).fill('25')
  await page.screenshot({path:path.join(evidence,'confirm-phone.png'),fullPage:true})
  await page.getByRole('button',{name:'Confirm & climb +250 m',exact:true}).click()
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-metres','250')
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-motion','celebrating')
  await expect(page.getByRole('status')).toContainText('Into the glen reached!')
  let ledger = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!),ledgerKey)
  expect(ledger.events).toHaveLength(1)
  expect(ledger.events[0]).toMatchObject({source:'manual',items:25,action:'folding'})
  await page.locator('.trail-reward[open]').waitFor({state:'visible'})
  while (await page.locator('.trail-reward[open]').count()) await page.locator('.trail-reward[open] button').click()
  await page.getByRole('button',{name:'Pause timer',exact:true}).click()
  const paused = await page.getByLabel('Session timer').innerText()
  await page.waitForTimeout(1200)
  expect(await page.getByLabel('Session timer').innerText()).toBe(paused)
  await expect(page.getByRole('button',{name:'Bank this batch'})).toBeDisabled()
  await page.getByRole('button',{name:'Save for later'}).click()
  await page.reload()
  await page.getByRole('button',{name:'Continue your session',exact:true}).click()
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-metres','250')
  await expect(page.getByLabel('Session timer')).toHaveText(paused)
  await page.getByRole('button',{name:'Resume timer',exact:true}).click()
  await page.getByRole('button',{name:'Bank this batch'}).click()
  await page.getByLabel('Hung up',{exact:true}).check()
  await page.getByLabel('Completed items',{exact:true}).fill('3')
  await page.getByRole('button',{name:'Confirm & climb +30 m',exact:true}).click()
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-metres','280')
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-motion','walking')
  await page.getByRole('button',{name:'Bank this batch'}).click()
  await page.getByLabel('Completed items',{exact:true}).fill('20')
  await page.getByRole('button',{name:'Cancel batch'}).click()
  ledger = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!),ledgerKey)
  expect(ledger.events).toHaveLength(2)
  await page.setViewportSize({width:844,height:390})
  await page.screenshot({path:path.join(evidence,'session-landscape.png'),fullPage:true})
  for (const size of [{width:844,height:390},{width:667,height:375},{width:320,height:740}]) {
    await page.setViewportSize(size)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (size.width > size.height) {
      for (const name of ['Bank this batch','Finish session','Save for later']) {
        const box = await page.getByRole('button',{name,exact:true}).boundingBox()
        expect(box!.y + box!.height, name).toBeLessThanOrEqual(size.height)
      }
    }
    await page.getByRole('button',{name:'Bank this batch'}).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button',{name:'Cancel batch'}).click()
  }
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'Finish session',exact:true}).click()
  await expect(page.getByText('28 items banked. 280 Laundry Metres earned.')).toBeVisible()
  await expect(page.getByText('Manually confirmed · 10 metres per item')).toBeVisible()
  await page.screenshot({path:path.join(evidence,'results-phone.png'),fullPage:true})
  await page.locator('.trail-reward[open]').waitFor({state:'visible'})
  while (await page.locator('.trail-reward[open]').count()) await page.locator('.trail-reward[open] button').click()
  await page.getByRole('button',{name:'View session history'}).click()
  await expect(page.locator('.session-history')).toContainText('28 items')
  const sessions = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!),sessionsKey)
  expect(sessions).toHaveLength(1)
  expect(sessions[0]).toMatchObject({items:28,base:280,metres:280,status:'finished',mode:'manual'})
  await page.reload()
  expect(await page.evaluate(() => localStorage.getItem('laundry-mountain:field-report:v1'))).toBe('preserve failed physical report')
  await page.goto('/?view=mountain')
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-metres','280')
})

test('optional photo is a temporary preview, never a count or a saved upload', async ({page}) => {
  await page.goto('/?view=home')
  await page.getByRole('button',{name:'Start a Laundry Session',exact:true}).click()
  await page.getByRole('button',{name:'Bank this batch'}).click()
  await page.getByText('Add a photo (optional)').click()
  await page.getByLabel('Batch photo',{exact:true}).setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5mQAAAAASUVORK5CYII=','base64')})
  await expect(page.getByAltText('Your completed laundry batch')).toBeVisible()
  await expect(page.getByLabel('Completed items',{exact:true})).toHaveValue('1')
  await page.getByRole('button',{name:'Cancel batch'}).click()
  await page.getByRole('button',{name:'Bank this batch'}).click()
  await expect(page.getByAltText('Your completed laundry batch')).toHaveCount(0)
  expect(await page.getByLabel('Batch photo',{exact:true}).inputValue()).toBe('')
  expect(await page.evaluate(key => localStorage.getItem(key),ledgerKey)).toBeNull()
})

test('zero-item finish awards nothing; a failed metadata write recovers from the ledger', async ({page}) => {
  await page.goto('/?view=home')
  await page.getByRole('button',{name:'Start a Laundry Session',exact:true}).click()
  await page.getByRole('button',{name:'Finish session',exact:true}).click()
  await expect(page.getByText('No batches banked this time.')).toBeVisible()
  expect(await page.evaluate(key => localStorage.getItem(key),ledgerKey)).toBeNull()
  await page.goto('/?view=home')
  await page.getByRole('button',{name:'Start a Laundry Session',exact:true}).click()
  await page.evaluate(key => {
    const original=Storage.prototype.setItem
    Storage.prototype.setItem=function(k,v){if(k===key) throw new DOMException('Full','QuotaExceededError'); original.call(this,k,v)}
  },sessionsKey)
  await page.getByRole('button',{name:'Bank this batch'}).click()
  await page.getByLabel('Completed items',{exact:true}).fill('4')
  await page.getByRole('button',{name:'Confirm & climb +40 m',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Saving was interrupted')
  await expect(page.getByRole('button',{name:'Confirm & climb +40 m',exact:true})).toBeDisabled()
  await page.reload()
  await page.getByRole('button',{name:'Continue your session',exact:true}).click()
  await expect(page.locator('.climb-scene')).toHaveAttribute('data-metres','40')
  await expect(page.locator('.manual-stats')).toContainText('4items')
  const ledger=await page.evaluate(key => JSON.parse(localStorage.getItem(key)!),ledgerKey)
  expect(ledger.events).toHaveLength(1)
})
