import { useCallback, useEffect, useRef, useState } from 'react'
import type { CSSProperties } from 'react'
import { ArrowLeft, ArrowRight, Check, Flame, Flag, Home, Leaf, Mountain, Pause, Play, Shirt, Sparkles, Timer, Waves, Layers, History, ShieldCheck } from 'lucide-react'
import { CameraLab } from './CameraLab'
import type { Calibration, Observation } from './CameraLab'
import { MountainScene } from './MountainScene'
import { BEN_NEVIS, GAME } from '../domain/config'
import { expeditionProgress } from '../domain/expedition'
import { appendEvent, emptyLedger, parseLedger, STORAGE_KEY, summary } from '../domain/ledger'
import type { LaundryEvent } from '../domain/events'
import './game.css'

type Screen = 'home' | 'setup' | 'camera' | 'live' | 'results' | 'sessions' | 'mountain'
interface Session { id: string; startedAt: number; endedAt?: number; load: string; goal: number; items: number; metres: number; base: number; status: 'active' | 'finished'; reason?: string }
const SESSION_KEY = 'laundry-mountain:game-sessions:v1'
const loads = [{ name: 'Everyday', Icon: Shirt }, { name: 'Delicates', Icon: Leaf }, { name: 'Towels', Icon: Layers }, { name: 'Bedding', Icon: Waves }, { name: 'Activewear', Icon: Sparkles }, { name: 'Mixed load', Icon: Layers }]
const format = (n: number) => n.toLocaleString(undefined, { maximumFractionDigits: 1 })
const time = (n: number) => `${String(Math.floor(n / 60)).padStart(2, '0')}:${String(n % 60).padStart(2, '0')}`
function initialScreen(): Screen { const s = new URLSearchParams(location.search).get('view'); return s === 'sessions' ? 'sessions' : s === 'mountain' ? 'mountain' : 'home' }
function readSessions(): Session[] { const raw = localStorage.getItem(SESSION_KEY); if (!raw) return []; const v: unknown = JSON.parse(raw); if (!Array.isArray(v) || v.some(s => !s || typeof s.id !== 'string' || !Number.isFinite(s.startedAt) || !Number.isFinite(s.items) || !Number.isFinite(s.metres) || !Number.isFinite(s.base) || !['active', 'finished'].includes(s.status))) throw new Error('Saved sessions could not be read. Existing data has been kept.'); return v as Session[] }
export function GameApp() {
  const [screen, setScreen] = useState<Screen>(initialScreen), [load, setLoad] = useState('Everyday'), [goal, setGoal] = useState(20)
  const [error, setError] = useState(''), blocked = useRef(false)
  const [ledger, setLedger] = useState(() => { try { return parseLedger(localStorage.getItem(STORAGE_KEY)) } catch { return emptyLedger() } })
  const ledgerRef = useRef(ledger)
  const [sessions, setSessions] = useState<Session[]>(() => { try { return readSessions() } catch { return [] } }), sessionsRef = useRef(sessions)
  const [current, setCurrent] = useState<Session | null>(null), run = useRef<Session | null>(null)
  const [calibration, setCalibration] = useState<Calibration | null>(null), [paused, setPaused] = useState(false)
  const [observation, setObservation] = useState<Observation | null>(null), [clock, setClock] = useState(Date.now()), [close, setClose] = useState(false)
  const [burst, setBurst] = useState('')
  useEffect(() => { try { parseLedger(localStorage.getItem(STORAGE_KEY)); readSessions() } catch (e) { blocked.current = true; setError(e instanceof Error ? e.message : 'Storage is unavailable. Progress cannot be saved.') } }, [])
  function navigate(next: Screen) { history.pushState(null, '', `/?view=${next}`); setScreen(next); window.scrollTo(0, 0) }
  const saveSession = useCallback((value: Session) => { const list = [value, ...sessionsRef.current.filter(s => s.id !== value.id)]; localStorage.setItem(SESSION_KEY, JSON.stringify(list)); sessionsRef.current = list; setSessions(list); setCurrent(value) }, [])
  const finish = useCallback((reason = 'Session finished') => {
    if (!run.current) return
    const value = { ...run.current, endedAt: Date.now(), status: 'finished' as const, reason }; run.current = null
    try { saveSession(value) } catch { blocked.current = true; setCurrent(value); setError('Session results could not be saved. Your last saved mountain position is preserved.') }
    setPaused(false); setScreen('results'); history.replaceState(null, '', '/?view=results')
  }, [saveSession])
  useEffect(() => { const pop = () => { if (run.current) finish('Left the live session'); else setScreen(initialScreen()) }; window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop) }, [finish])
  useEffect(() => { document.title = `Laundry Mountain · ${screen === 'home' ? 'Higher ground' : screen === 'live' ? 'Your live climb' : screen}` }, [screen])
  useEffect(() => { if (screen !== 'live') return; const t = setInterval(() => setClock(Date.now()), 1000); return () => clearInterval(t) }, [screen])
  useEffect(() => { if (!burst) return; const t = setTimeout(() => setBurst(''), 2200); return () => clearTimeout(t) }, [burst])
  const ready = useCallback((c: Calibration | null) => setCalibration(c), [])
  const observe = useCallback((o: Observation) => setObservation(o), [])
  const accept = useCallback((evidence: string) => {
    const s = run.current; if (!s || blocked.current) return
    const event: LaundryEvent = { id: crypto.randomUUID(), sessionId: s.id, at: Date.now(), action: 'folding', source: 'camera', items: 1, evidence }
    const next = appendEvent(ledgerRef.current, event), earned = summary(next).lifetimeMetres - summary(ledgerRef.current).lifetimeMetres
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); ledgerRef.current = next; setLedger(next)
      const updated = { ...s, items: s.items + 1, base: s.base + GAME.metresPerItem, metres: s.metres + earned }; run.current = updated; saveSession(updated); setBurst(`+${format(earned)} m`)
    } catch { blocked.current = true; setError('Storage failed. Session stopped at the last saved position.'); finish('Storage failed') }
  }, [finish, saveSession])
  function start() {
    if (!calibration || blocked.current) return
    const s: Session = { id: crypto.randomUUID(), startedAt: Date.now(), load, goal, items: 0, metres: 0, base: 0, status: 'active' }
    try { saveSession(s) } catch { blocked.current = true; setError('Session could not be saved. Check that browser storage is enabled.'); return }
    run.current = s; setClock(s.startedAt); setPaused(false); navigate('live')
  }
  const stats = summary(ledger), progress = expeditionProgress(stats.mountainMetres)
  const elapsed = current ? Math.max(0, Math.floor(((current.endedAt ?? clock) - current.startedAt) / 1000)) : 0
  const sessionEvents = current ? ledger.events.filter(e => e.sessionId === current.id) : []
  let streak = 0, last = 0; for (const e of sessionEvents) { streak = e.at - last > GAME.momentumResetMs ? 1 : streak + 1; last = e.at }
  if (clock - last > GAME.momentumResetMs) streak = 0
  const multiplier = GAME.momentum.find(t => streak >= t.items)?.multiplier ?? 1
  function scenic(compact = false) { return <div className={`game-scenic ${compact ? 'compact' : ''}`}><MountainScene metres={stats.mountainMetres} close={close} /><div className="scenic-title"><span>YOUR CURRENT MOUNTAIN</span><h2>Ben Nevis</h2><p>Scottish Highlands · Summit 1,345 m</p></div>{!compact && <div className="scenic-foot"><p>Small loads.<br /><strong>Higher ground.</strong></p><div className="progress-ring" style={{ '--progress': `${stats.percent * 3.6}deg` } as CSSProperties}><strong>{format(stats.percent)}%</strong></div></div>}</div> }
  return <div className={`game-shell ${screen === 'live' || screen === 'camera' ? 'session-shell' : ''}`}>
    <header className="game-header">{screen === 'home' ? <img src="/brand/laundry-mountain.png" alt="Laundry Mountain. Real Laundry. Higher Ground." /> : <button className="icon-button" aria-label="Back to home" onClick={() => run.current ? finish('Returned home') : navigate('home')}><ArrowLeft /></button>}{screen !== 'home' && <strong>{screen === 'setup' ? 'Start a session' : screen === 'camera' ? 'Get ready to climb' : screen === 'live' ? 'Ben Nevis' : screen === 'sessions' ? 'Your sessions' : screen === 'mountain' ? 'Your mountain' : 'Session results'}</strong>}<span className="local-badge">{screen === 'live' ? time(elapsed) : <><ShieldCheck size={14} /> Saved on this phone</>}</span></header>
    {error && <p role="alert" className="error">{error}</p>}
    <main className="game-main">
      {screen === 'home' && <><div className="game-heading"><span className="game-eyebrow">SMALL HABITS. HIGHER HORIZONS.</span><h1>Your next climb<br />starts here.</h1><p>Clean clothes. A little higher.</p></div>{scenic()}<div className="game-stat-row"><div><Mountain /><strong>{format(stats.lifetimeMetres)} m</strong><span>Laundry Metres</span></div><div><Shirt /><strong>{stats.items}</strong><span>Items counted</span></div><div><Flame /><strong>{stats.best}</strong><span>Best momentum</span></div></div><button className="primary game-cta" onClick={() => navigate('setup')}><Play size={18} fill="currentColor" /> Start a laundry session <ArrowRight size={18} /></button><button className="checkpoint-card" onClick={() => navigate('mountain')}><Flag /><span><small>NEXT CHECKPOINT</small><strong>{progress.next?.name ?? 'Summit reached'}</strong><span>{progress.next ? `${format(progress.remaining)} m to go` : 'Your laundry brought you all the way'}</span></span><ArrowRight /></button></>}
      {screen === 'setup' && <><div className="game-heading"><h1>A fresh load.<br />A little higher.</h1><p>Make everyday laundry a small adventure.</p></div><fieldset className="load-picker"><legend>What are you folding?</legend><div>{loads.map(({ name, Icon }) => <button key={name} aria-pressed={load === name} onClick={() => setLoad(name)}><Icon size={29} />{name}{load === name && <Check className="choice-check" size={14} />}</button>)}</div></fieldset><fieldset className="goal-picker"><legend>Your session goal</legend><div>{[10, 20, 30].map(n => <button key={n} aria-pressed={goal === n} onClick={() => setGoal(n)}><strong>{n}</strong> items</button>)}</div><p>The camera counts completed items as you go.</p></fieldset>{scenic(true)}<div className="privacy-card"><Leaf /><p><strong>Your chore is the controller.</strong><br />Front camera processing stays on your phone.</p></div><button className="primary game-cta" onClick={() => navigate('camera')}>Set up my camera <ArrowRight size={18} /></button></>}
      {(screen === 'camera' || screen === 'live') && <div className={`game-session ${screen === 'live' ? 'is-live' : ''}`}><div className="game-camera-column">{screen === 'camera' && <div className="game-heading"><h1>Frame it.<br />Then climb.</h1><p>Screen facing you, phone in landscape, about 1–1.5 m from the table. Show the pickup spot, folding area and completed stack.</p></div>}<CameraLab active={screen === 'live'} paused={paused} presentation="game" onEvent={accept} onObservation={observe} onReady={ready} onInterrupt={finish} onStart={start} guideSession={{ active: screen === 'live', elapsed, count: current?.items ?? 0, stage: observation?.stage }} />{screen === 'live' && <p className="live-instruction" role="status">{paused ? 'Paused. Your place is saved. Resume before picking up your next item.' : observation?.reason ?? 'Take one item from the pickup spot. Fold, place in Completed, then withdraw your hands.'}</p>}</div><section className="game-climb-column"><div className="game-heading"><h1>Every item takes you higher.</h1><p>{paused ? 'Take a breath. Your mountain will wait.' : 'One small load. Real progress.'}</p></div>{scenic()} {burst && <div className="game-burst" role="status">{burst}</div>}<div className="game-stat-row"><div><Shirt /><strong>{current?.items ?? 0}</strong><span>Items counted</span></div><div><Mountain /><strong>+{format(current?.metres ?? 0)} m</strong><span>Session climb</span></div><div><Flame /><strong>×{multiplier.toFixed(2)}</strong><span>Momentum</span></div></div>{screen === 'live' && <><div className="goal-progress"><span>SESSION GOAL</span><strong>{current?.items ?? 0} / {goal} items</strong><progress aria-label="Session item goal" max={goal} value={Math.min(goal, current?.items ?? 0)} /></div><div className="game-live-buttons"><button onClick={() => setPaused(p => !p)}>{paused ? <Play size={17} /> : <Pause size={17} />}{paused ? 'Resume' : 'Pause'}</button><button className="primary" onClick={() => finish()}>Finish session <Check size={17} /></button></div></>}</section></div>}
      {screen === 'results' && current && <><div className="results-heading"><img src="/brand/laundry-mountain.png" alt="Laundry Mountain" /><h1>{current.items ? 'Another load higher!' : 'Session finished.'}</h1><p>Your results, saved on this phone.</p></div><div className="game-stat-row result-stats"><div><Mountain /><strong>+{format(current.metres)} m</strong><span>Laundry Metres</span></div><div><Shirt /><strong>{current.items}</strong><span>Items counted</span></div><div><Timer /><strong>{time(elapsed)}</strong><span>Session time</span></div></div><section className="breakdown"><h2>Your climb, item by item</h2><p><span>Base metres</span><strong>{format(current.base)} m</strong></p><p><span>Momentum bonus</span><strong>+{format(current.metres - current.base)} m</strong></p><p><span>Total Laundry Metres</span><strong>{format(current.metres)} m</strong></p></section>{!current.items && <div className="privacy-card"><Leaf /><p><strong>No items were detected.</strong><br />Your saved position is unchanged. Review the camera test when you are ready.</p></div>}{current.reason !== 'Session finished' && <p className="small-print">{current.reason}</p>}{scenic(true)}<button className="primary game-cta" onClick={() => navigate('mountain')}>Back to my mountain <ArrowRight size={18} /></button><button className="game-cta" onClick={() => navigate('sessions')}>View session history</button><a className="diagnostics-link" href="/">Open test diagnostics</a></>}
      {screen === 'mountain' && <><div className="game-heading"><span className="game-eyebrow">YOUR FIRST EXPEDITION</span><h1>Ben Nevis</h1><p>A mountain of laundry. One item at a time.</p></div>{scenic()}<div className="view-control"><button aria-pressed={!close} onClick={() => setClose(false)}>Full mountain</button><button aria-pressed={close} onClick={() => setClose(true)}>Climb view</button></div><div className="mountain-progress"><strong>{format(stats.mountainMetres)} / 1,345 m</strong><progress aria-label="Ben Nevis progress" value={stats.mountainMetres} max={1345} /></div><ol className="game-checkpoints">{BEN_NEVIS.checkpoints.map(c => <li key={c.metres} className={stats.mountainMetres >= c.metres ? 'reached' : ''}><span>{stats.mountainMetres >= c.metres ? <Check size={17} /> : <Flag size={15} />}</span><div><strong>{c.name}</strong><p>{c.description}</p></div><small>{format(c.metres)} m</small></li>)}</ol><p className="small-print">Illustrative game route. Laundry Metres are your game progress.</p><button className="primary game-cta" onClick={() => navigate('setup')}>Keep climbing <ArrowRight size={18} /></button></>}
      {screen === 'sessions' && <><div className="game-heading"><h1>Small loads.<br />Lasting progress.</h1><p>Your laundry adventures, saved on this phone.</p></div>{!sessions.length ? <section className="history-empty"><History size={38} /><h2>Your journey starts with one load.</h2><p>Finish a session and its results will be waiting here.</p><button className="primary" onClick={() => navigate('setup')}>Start your first session <ArrowRight size={16} /></button></section> : <div className="session-history">{sessions.map(s => <button key={s.id} onClick={() => { setCurrent(s); setClock(s.endedAt ?? s.startedAt); navigate('results') }}><span className="history-icon"><Shirt /></span><span><strong>{s.load} · {s.items} items</strong><small>{new Date(s.startedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} · {s.status === 'active' ? 'Left before finishing' : time(Math.max(0, Math.floor(((s.endedAt ?? s.startedAt) - s.startedAt) / 1000)))}</small></span><strong>+{format(s.metres)} m</strong><ArrowRight size={17} /></button>)}</div>}<div className="privacy-card"><ShieldCheck /><p><strong>Your progress travels with this browser.</strong><br />Use this phone and browser to return to the same place.</p></div></>}
      {screen !== 'live' && <p className="validation-note">Camera detection is still being validated. <a href="/">Folding test</a></p>}
    </main>
    {screen !== 'live' && screen !== 'camera' && <nav className="game-nav" aria-label="Game navigation">{([{ s: 'home', label: 'Home', Icon: Home }, { s: 'mountain', label: 'Mountain', Icon: Mountain }, { s: 'sessions', label: 'Sessions', Icon: History }] as const).map(({ s, label, Icon }) => <button key={s} aria-current={screen === s ? 'page' : undefined} onClick={() => navigate(s)}><Icon size={22} /><span>{label}</span></button>)}</nav>}
  </div>
}

